# Generated by Django 3.2.13 on 2022-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_connectionsmysql'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedfield',
            name='nameBank',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
